server:
  port: 8080

spring:
  redis:
    host: 192.168.74.131
    port: 6379
    password: 224336


    #指定redis底层客户端实现
    client-type: jedis

#  lettuce:
#    pool:
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 10
#
#      # 连接池中的最大空闲连接
#      max-idle: 10
#
#      # 连接池中的最小空闲连接
#      min-idle: 0
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1ms


  jedis:
    pool:
# 连接池最大连接数（使用负值表示没有限制）
      max-active: 10

# 连接池中的最大空闲连接
      max-idle: 10

# 连接池中的最小空闲连接
      min-idle: 0
# 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms
