server:
  port: 8080

spring:
  #指定spring cache缓存的类型
  cache:
    type: redis
    redis:
      cache-null-values: true #缓存空值 预防缓存穿透

  redis:
    #host: 192.168.74.131
    #port: 6379
#    sentinel:
#      master: mymaster
#      nodes: 192.168.74.132:26379, 192.168.74.132:26380, 192.168.74.132:26381
    cluster:
      #命名的最多转发次数
      max-redirects: 3
      nodes: 192.168.74.132:6381, 192.168.74.132:6382, 192.168.74.132:6383,
            192.168.74.132:6384, 192.168.74.132:6385, 192.168.74.132:6386
    password: 224336

    #指定redis底层客户端实现
    client-type: lettuce

    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10

        # 连接池中的最大空闲连接
        max-idle: 10

        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#    jedis:
#      pool:
#      # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 10
#
#        # 连接池中的最大空闲连接
#        max-idle: 10
#
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms

#==============================数据库相关配置========================================
#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xdclass_redis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 224336

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

